galaxy_info:
  author: Mats Blomdahl
  description: Provisioning of common system configuration.

  min_ansible_version: 2.7

  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - Bionic

  galaxy_tags:
    - common
    - smsi

dependencies: []
