
galaxy_info:
  author: Mats Blomdahl
  description: Provisioning of Python 3 pip and virtualenv capabilities.

  min_ansible_version: 2.7

  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - Bionic

  galaxy_tags:
    - python
    - pypi

dependencies: []
