---

- name: configure hadoop core-site.xml
  copy:
    src: core-site.xml
    dest: /home/hadoop/hadoop/etc/hadoop/core-site.xml
  become: yes
  become_user: hadoop
  tags: hdfs

- name: configure hadoop hdfs-site.xml
  copy:
    src: hdfs-site.xml
    dest: /home/hadoop/hadoop/etc/hadoop/hdfs-site.xml
  become: yes
  become_user: hadoop
  tags: hdfs

...
