---

- name: configure hadoop core-site.xml
  copy:
    src: core-site.xml
    dest: /home/hadoop/hadoop/etc/hadoop/core-site.xml
  become: yes
  become_user: hadoop
  tags: hdfs

- name: configure hadoop hdfs-site.xml
  copy:
    src: hdfs-site.xml
    dest: /home/hadoop/hadoop/etc/hadoop/hdfs-site.xml
  become: yes
  become_user: hadoop
  tags: hdfs

- name: configure hadoop mapred-site.xml
  copy:
    src: mapred-site.xml
    dest: /home/hadoop/hadoop/etc/hadoop/mapred-site.xml
  become: yes
  become_user: hadoop
  tags: hdfs

- name: configure hadoop yarn-site.xml
  copy:
    src: yarn-site.xml
    dest: /home/hadoop/hadoop/etc/hadoop/yarn-site.xml
  become: yes
  become_user: hadoop
  tags: hdfs

- name: configure hadoop slaves list
  template:
    src: slaves.j2
    dest: /home/hadoop/hadoop/etc/hadoop/slaves
  become: yes
  become_user: hadoop
  tags: hdfs

...
