---

- block:
    - name: install python3-pip and python3-venv
      apt:
        name: ['python3-pip', 'python3-venv']
        state: present
      tags: python

    - name: install modern pip version
      pip:
        name: pip
        version: 18.1
        executable: pip3
        state: present
      tags: python

    - name: install virtualenv
      pip:
        name: virtualenv
        version: 16.2.0
        executable: pip3
        state: present
      tags: python

  when: ansible_distribution == 'Ubuntu'

- block:
    - name: install centos-release-scl
      yum:
        name: centos-release-scl
        state: present

    - name: install rh-python36
      yum:
        name: rh-python36
        state: present

    - name: install scl pip-18.1
      shell: scl enable rh-python36 "pip install pip==18.1"
      register: rhel7_pip_install
      changed_when: rhel7_pip_install.stdout.find('already satisfied') == -1

    - name: install scl virtualenv-16.2.0
      shell: scl enable rh-python36 "pip install virtualenv==16.2.0"
      register: rhel7_virtualenv_install
      changed_when: rhel7_virtualenv_install.stdout.find('already satisfied') == -1

  when: ansible_distribution == 'CentOS'

...
