---

- name: add o3 routing to /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK o3-common"
    block: "{{ etc_hosts_routing }}"
    state: "{{ 'present' if etc_hosts_routing else 'absent' }}"
  tags: common

- name: create hadoop user
  user:
    name: hadoop
    uid: 1001
    comment: "Cluster user"
    shell: /bin/bash
  tags: common

- name: set up authorized_keys for hadoop user
  authorized_key: user=hadoop key="{{ item }}"
  with_file:
    - public_keys/hadoop_id_rsa.pub
    - public_keys/mblomdahl_id_rsa.pub
  tags: common

- name: add private key for hadoop user
  copy:
    dest: /home/hadoop/.ssh/id_rsa
    content: "{{ hadoop_id_rsa }}"
    owner: hadoop
    group: hadoop
    mode: 0600
  tags: common

- name: add public key for hadoop user
  copy:
    src: public_keys/hadoop_id_rsa.pub
    dest: /home/hadoop/.ssh/id_rsa.pub
    owner: hadoop
    group: hadoop
    mode: 0644
  tags: common

- name: add ssh config for hadoop user
  copy:
    dest: /home/hadoop/.ssh/config
    content: |
      Host o3-*
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
        LogLevel ERROR
    owner: hadoop
    group: hadoop
  tags: common

- name: install jdk 8 (ubuntu)
  apt:
    name: openjdk-8-jre
    cache_valid_time: 86400
    state: present
  when: ansible_distribution == 'Ubuntu'
  tags: common

- name: install jdk 8 (centos)
  yum:
    name: java-1.8.0-openjdk
    state: present
  when: ansible_distribution == 'CentOS'
  tags: common

...
