---

- name: create airflow user
  user:
    name: airflow
    uid: 1002
    comment: "Airflow user"
    shell: /bin/bash
  tags: airflow

- name: create ~/airflow_home directory structure
  file:
    path: /home/airflow/{{ item }}
    state: directory
  with_items:
    - airflow_home
    - airflow_home/dags
    - airflow_home/logs
  become: yes
  become_user: airflow
  tags: airflow

- name: symlink ~/airflow_home/dags/airflow -> ~/hdl/current/hdl/airflow/dags
  file:
    src: /home/airflow/hdl/current/hdl/airflow/dags
    dest: /home/airflow/airflow_home/dags/airflow
    state: link
    force: yes
  become: yes
  become_user: airflow
  tags: airflow

- name: template airflow config
  template:
    src: airflow.cfg.j2
    dest: /home/airflow/airflow_home/airflow.cfg
  become: yes
  become_user: airflow
  tags: airflow

- name: create directory structure for hdl code
  file:
    path: /home/airflow/{{ item }}
    state: directory
  with_items:
    - hdl
    - hdl/releases
  become: yes
  become_user: airflow
  tags: airflow

- name: symlink ~/hdl/current -> ~/hdl/releases/o3
  file:
    src: /home/airflow/hdl/releases/o3
    dest: /home/airflow/hdl/current
    state: link
    force: yes
  become: yes
  become_user: airflow
  tags: airflow

- name: checkout code base
  git:
    repo: https://github.com/mblomdahl/o3.git
    version: feature/airflow
    dest: /home/airflow/hdl/releases/o3
    accept_hostkey: yes
  become: yes
  become_user: airflow
  tags: airflow

- block:
    - name: create airflow python3 virtualenv (Ubuntu)
      shell: python3 -m venv /home/airflow/pyenv
      args:
        creates: /home/airflow/pyenv
      become: yes
      become_user: airflow
      tags: airflow

    - name: install pip requirements.txt (Ubuntu)
      shell: SLUGIFY_USES_TEXT_UNIDECODE=yes /home/airflow/pyenv/bin/pip install
             -r /home/airflow/hdl/current/requirements.txt
      become: yes
      become_user: airflow
      register: pyenv_pip_install_requirements
      changed_when: "'Successfully built' in pyenv_pip_install_requirements.stdout"
      tags: airflow

  when: ansible_distribution == 'Ubuntu'

- block:
    - name: create airflow python3 virtualenv (CentOS)
      shell: scl enable rh-python36 'virtualenv -p python3 /home/airflow/pyenv'
      args:
        creates: /home/airflow/pyenv
      become: yes
      become_user: airflow
      tags: airflow

    - name: install pip requirements (CentOS)
      shell: scl enable rh-python36 'SLUGIFY_USES_TEXT_UNIDECODE=yes
             /home/airflow/pyenv/bin/pip install -r /home/airflow/hdl/current/requirements.txt'
      become: yes
      become_user: airflow
      register: scl_pip_install_requirements
      changed_when: "'Successfully built' in scl_pip_install_requirements.stdout"
      tags: airflow

  when: ansible_distribution == 'CentOS'

- name: template airflow-environment
  template:
    src: environment.j2
    dest: /home/airflow/airflow-environment
  become: yes
  become_user: airflow
  tags: airflow

- name: source airflow-environment in .bashrc
  blockinfile:
    path: /home/airflow/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK o3-airflow"
    block: |
      set -a
      source /home/airflow/airflow-environment
  become: yes
  become_user: airflow
  tags: airflow

- name: start postgres database
  docker_container:
    name: postgres
    image: postgres:9
    state: started
    restart_policy: unless-stopped
    volume_driver: local
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env:
      POSTGRES_DB: airflow
      POSTGRES_USER: hdl
      POSTGRES_PASSWORD: hdl
  tags: airflow

- name: template airflow services
  template:
    src: airflow-{{ item }}.service.j2
    dest: /etc/systemd/system/airflow-{{ item }}.service
  with_items:
    - webserver
    - scheduler
  register: add_airflow_services
  tags: airflow, systemd

- name: run daemon-reload
  shell: systemctl daemon-reload
  when: add_airflow_services is changed
  tags: airflow, systemd

- name: set airflow services to running and auto-starting
  service:
    name: airflow-{{ item }}
    state: started
    enabled: yes
  with_items:
    - webserver
    - scheduler
  tags: airflow, systemd

...
